project:
  type: website

website:
  title: "bhrigukumar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: miipw.qmd
        text: miipw
      - href: test.qmd
        text: textshiny

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

