project:
  type: website

website:
  title: "bhrigukumar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      - href: miipw.qmd
        text: miipw
      - href: Resume.qmd
        text: myResume
      - href: portfolio.qmd
        text: portfolio
      - href: projects.qmd
        text: projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

